### PR TITLE
Upgrading to SQLite 3.8.4.3

### PR DESCRIPTION
**Pull request by paingheinthu**

### CODE REVIEW

**Comment by peterhuene** [comment]
Thanks @paingheinthu!  I'll get this merged in tomorrow (I'm in the PDT timezone) and push up a new NuGet package.

**Comment by paingheinthu** [comment]
Thank for accept my request.

**Comment by saramgsilva** [comment]
I have this issue :(  when i will publish the update?

**Comment by peterhuene** [comment]
Thanks for your contribution, @paingheinthu!  I will push a tag and NuGet package update shortly.

**Pull request merged**
