### PR TITLE
Add interrupt to faciliate Async

### PR DESCRIPTION
**Pull request by tofutim**
A small change, but I need it for to interrupt async stuff. Thanks for all the great work.

### CODE REVIEW

**Comment by peterhuene** [comment]
I no longer maintain this project, but I don't see the harm in merging this in.

**Comment by peterhuene** [comment]
Wait, sorry, was this missing a corresponding change to the header?

**Comment by tofutim** [comment]
Good catch, yes, I forgot to commit that. Let me do that. I can also help
be an official fork or contributor if you still need that.

**Comment by tofutim** [comment]
Should be there now.

**Comment by tofutim** [comment]
2nd pull. Do you also update the nuget?

**Comment by peterhuene** [comment]
I don't anymore.  I'd be happy to add you as an owner to the nuget package so you can update it if you wish (just need your nuget username).  If you'd like to become the official fork, I'll also update the README to point at yours.

**Comment by tofutim** [comment]
my nuget username is 'tofutim'

Let's wait on official fork though. Are you really done with this project?

**Comment by tofutim** [comment]
Yeah, I think you better pass it to me so I can increment the version.

**Comment by peterhuene** [comment]
Sorry, was on a 13 hour flight until a little while ago.  I've added you as a collaborator on my GitHub project (feel free to just change it to point at yours) and as an owner on the NuGet package.  Thanks!

**Comment by tofutim** [comment]
13 hour flight sounds fun. Where in the world did you go?

Best wishes,
Tim

**Comment by peterhuene** [comment]
Currently in Abu Dhabi.  Traveling to my honeymoon in the Seychelles.  Cheers!

**Comment by tofutim** [comment]
Wow! Congratulations. Have a wonderful honeymoon, and for goodness sake,
stop checking email from me. :)

**Pull request merged**
